### ISSUE TITLE
Add option to create note in DevonThink automatically

### ISSUE THREAD

**Issue by colinhahn** [guoc/excerptor#2] opened 2015-11-12 21:07 UTC
This is a feature request to add an option that creates a new note in DevonThink with the excerpt and other specified parameters (e.g., creator, link to original document).

Right now, my workflow is to select text in the PDF, right click and select the excerptor service, copying text to the clipboard, then going into DevonThink and creating a new note with the text (or using the DevonThink note shortcut to create a new note and pasting the clip into the note body). It would be great to eliminate the manual steps of creating a note and pasting the excerpt.

**Comment by guoc** [comment] 2015-11-12 21:58
The feature Excerpt To File might meet your requirement. In Excerptor's settings, switch to Excerpt To File, choose Location to DEVONthink's inbox. Then in PDF, select text and select Excerptor's another service Excerpt Selection To File.

**Comment by colinhahn** [comment] 2015-11-13 14:02
That's close, but there's a couple of problems with the workflow still.

1) The new items are not dropped directly into the global inbox. Instead, there is a newly created folder with the title of the document that I clipped from, with the clip inside. I end up with multiple folders, each with one clipping, if I make multiple extracts from a single document. This behavior occurs with the File Template Location set to both ~/Library/Application Support/DEVONthink Pro 2/Inbox/{{PDFFileName_NoExtension}} as well as ~/Library/Application Support/DEVONthink Pro 2/Inbox/.

2) When I view the file, it displays as unrendered md. I need to manually convert to RTF in order to see a properly formatted hyperlink. I tried changing the File Template Filename extension to .rtf, but that resulted in no clipping being made (it was as if I hadn't chosen the Extractor service at all). I tried a couple of times to verify that I hadn't misclicked.

What I would like is for the new clip to end directly in my inbox (not a folder within the inbox), with the note rendered. Is there a preference setting I am missing?

**Comment by guoc** [comment] 2015-11-13 23:04
1) I just noticed the issue that duplicated folders with same folder name are in DEVONthink's Inbox. Thank you for your message. The issue depends on DEVONthink's implementation. I have no way to fix it. But DEVONthink provides a way to merge folders. You can select duplicated folders and Control - Click to get merge in context menu. 

> This behavior occurs with the File Template Location set to both ~/Library/Application Support/DEVONthink Pro 2/Inbox/{{PDFFileName_NoExtension}} as well as ~/Library/Application Support/DEVONthink Pro 2/Inbox/

For the issue above, could you screenshot your config page?

2) The file template only supports plain text. Personally I prefer to use https://github.com/ttscoff/MMD-QuickLook/, with this, you can select your excerpt file and tap space bar to QuickLook the excerpt, and the link will be available to click. If you want edit the excerpt, there are lots of good Markdown editors available.

Please let me know if any questions.

**Comment by colinhahn** [comment] 2015-11-16 13:25
I've attached the screenshot for the extra subfolders issue.

![screen shot 2015-11-16 at 7 24 37 am](https://cloud.githubusercontent.com/assets/3891682/11182797/2373ced0-8c33-11e5-9dd4-00da8055c4d1.png)

**Comment by guoc** [comment] 2015-11-16 21:49
I couldn't reproduce the issue. Can we make it clearer?
You mean, with the settings in your screenshot, and then make multiple extracts from a single document, you'll get the file hierarchy below?

```
| Inbox
  | PDFFileName
     | ExcerptText1
  | PDFFileName
     | ExcerptText2
  | PDFFileName
     | ...
```

It seems the settings didn't take effect. Could you send me the preference file? ~/Library/Preferences/name.guoc.excerptor.Excerptor.plist

What's the version of your Excerptor, OS X, Preview/Skim, DEVONthink Pro?

Thank you.

**Comment by colinhahn** [comment] 2015-11-17 13:37
Your summary and picture is correct. However, now I'm getting an even more strange behavior.

I created a new PDF document for testing (the results of a Google search for DevonThink) and created some clips from Preview using Excerpt to File.

What is happening is that the excerpts are now being created in the global inbox, but each time, an empty new folder is being created with the title of the first PDF that I made clips from.

So, after creating two clippings, my global Inbox looks like:
| Inbox/
--| PDF1FileName/
--| PDF1FileName/
--| ExcerptTextfromPDF2_1.md
--| ExcerptTextfromPDF2_2.md

OS X 10.10.5, DevonThink Pro Office 2.8.7, Preview 8.0, Excerpter 1.1

There seem to be two preference files in my home library: name.guoc.excerptor.plist and name.guoc.excerptor.Excerptor.plist. I had to add a .txt to each file to attach them here.
[name.guoc.excerptor.Excerptor.plist.txt](https://github.com/guoc/excerptor/files/36712/name.guoc.excerptor.Excerptor.plist.txt)
[name.guoc.excerptor.plist.txt](https://github.com/guoc/excerptor/files/36711/name.guoc.excerptor.plist.txt)

**Comment by guoc** [comment] 2015-11-18 01:45
I setup as the system environment you give on my MacBook for testing. It's almost brand new system.
Then I restarted my system to make sure there is no preferences cache for Excerptor. Then copied your .plist file to overwrite my .plist and launch Excerptor.

For the previous issue, it still did not happen. Considering the new strange behaviours, I guess perhaps there are two or more Excerptor instances running. Could you open Activity Monitor in /Applications/Utilities/ and search Excerptor? If there are more than one Excerptor, the assumption could be verified, and it may be fixed by quitting them then reopening Excerptor or restarting system.

Another supposition is about DEVONthink's Inbox behaviours. The Inbox in DEVONthink's library and the Inbox in Finder (the path set in Excerptor's selection Location) are different. New files put into Finder's Inbox are imported to DEVONthink's Inbox, the original files in Finder's Inbox will be removed. That's why twice excerpt actions on a same PDF file will generate two duplicated folders if PDF file name is set as part of selection Location like default settings. Could you change the settings for Excerptor selection Location to a different folder? This would better be done after restarting system. If restarting system is not allowed in your situation, please use Activity Monitor to kill Excerptor.

I appreciate your patience.

**Comment by colinhahn** [comment] 2015-11-19 13:25
I confirmed that there's only one copy of Excerptor running. I'll test the
inbox locations later today.

Thanks for your help in working through this issue. And, thank you for
creating this utility!

**Comment by colinhahn** [comment] 2015-11-20 17:29
I just tried restarting the system and changing the folder location. I
experienced the same behavior: the clipped document showed up in my global
Inbox, and a new (empty) folder was created in the global Inbox with the
name of the first document that I clipped from (NOT the name of the file
that I clipped from when doing the experiment).

**Comment by guoc** [comment] 2015-11-20 19:56
Now the issue is, what you do in preferences does not affect how Excerptor works. The preferences' changes can be reflected in configuration file. Perhaps something about reading configuration files is wrong in my code. I'll check it and let you know if fixed.
Thank you.

**Comment by guoc** [comment] 2015-11-20 20:19
Do other preferences changes work? such as Content, and settings in other tabs Excerpt To Pasteboard. This will be helpful to locate bugs.

**Comment by colinhahn** [comment] 2015-11-20 21:07
I know that I made changes to the Excerpt to Pasteboard tab that modified
the content of the clipping, and those changes took effect. I will test
making other changes to the Excerpt to File tab.

**Comment by guoc** [comment] 2015-11-22 08:52
I just released an update. I don't know if it could fix the issue, because I still can not reproduce it. Could you check this new version? Thank you.

**Comment by colinhahn** [comment] 2015-11-24 13:39
Same problem occurs with 1.1.1.

**Comment by guoc** [comment] 2015-11-29 12:39
I am sorry. I still could not reproduce these issues.

If you'd still like try a full reinstallation for Excerptor (this is the last thing I can think of), these are wiki pages [Uninstallation](https://github.com/guoc/excerptor/wiki/Uninstallation) and [Installation](https://github.com/guoc/excerptor/wiki/Excerptor-Installation) (a little changes since the beginning).

Thank you again for your patience.

**Closed as completed** 2017-02-21 12:49 UTC
